return {
  -- 'iabdelkareem/csharp.nvim',
  -- dependencies = {
  --   'williamboman/mason.nvim', -- Required, automatically installs omnisharp
  --   'mfussenegger/nvim-dap',
  --   'Tastyep/structlog.nvim', -- Optional, but highly recommended for debugging
  -- },
  -- config = function()
  --   require('mason').setup()
  --   require('csharp').setup {
  --     lsp = {
  --       omnisharp = {
  --         enabled = false,
  --       },
  --       roslyn = {
  --         enabled = true,
  --         cmd_path = '~/.local/share/nvim/roslyn/Microsoft.CodeAnalysis.LanguageServer.dll',
  --       },
  --     },
  --   }
  -- end,
}
